version: '3'
services:
    netbox:
        build:
          context: .
          args:
            - BRANCH=${BRANCH-v2.2-beta2}
        image: mastermindg/netbox:beta
        depends_on:
        - postgres
        env_file: 
          - ./include/netbox.env
          - ./include/napalm.env
        volumes:
        - ./config:/etc/netbox-nginx/
        - ./netbox-static-files:/opt/netbox/netbox/static
    nginx:
        image: nginx:1.11-alpine
        command: nginx -g 'daemon off;' -c /etc/netbox-nginx/nginx.conf
        depends_on:
        - netbox
        ports:
        - "80:80"
        volumes:
        - ./netbox-static-files:/opt/netbox/netbox/static
        - ./config:/etc/netbox-nginx/
    postgres:
        image: postgres:9.6-alpine
        env_file: ./include/postgres.env
        volumes:
        - ./pgdata:/var/lib/postgresql/data
    client:
        build:
            context: ./client
        image: mastermindg/netbox_client
        depends_on:
        - netbox
        env_file:
        - ./client/client.env
