version: '3'
services:
    netbox:
        build:
          context: .
          args:
            - BRANCH=${BRANCH-v2.2-beta2}
        image: mastermindg/netbox:beta
        ports:
        - "80:80"
        depends_on:
        - postgres
        env_file: 
          - ./include/netbox.env
          - ./include/napalm.env
    postgres:
        image: postgres:9.6-alpine
        env_file: ./include/postgres.env
        volumes:
        - ./pgdata:/var/lib/postgresql/data
    client:
        build:
            context: ./client
        image: mastermindg/netbox_client
        depends_on:
        - netbox
        env_file:
        - ./client/client.env
